name: mijn.doedejaarsma.nl
recipe: laravel

config:
  webroot: public
  xdebug: false
  php: 7.3

services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

  PMA:
    type: phpmyadmin
    portforward: true

  appserver:
    run:
      - 'php artisan passport:install'

proxy:
  appserver:
    - mijn-doedejaarsma.lndo.site

  mailhog:
    - hog-mijn-doedejaarsma.lndo.site
    - mailhog-mijn-doedejaarsma.lndo.site

  PMA:
    - pma-mijn-doedejaarsma.lndo.site
