name: mijn.doedejaarsma.nl
recipe: laravel
config:
  webroot: public
  xdebug: true
  php: 7.2
services:
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  PMA:
    type: phpmyadmin
proxy:
  appserver:
    - mijn-doedejaarsma.lndo.site
