name: mijn.doedejaarsma.nl
recipe: laravel

config:
  webroot: public
  xdebug: false
  php: 7.2

services:
  node:
    type: node

  mailhog:
    type: mailhog
    hogfrom:
      - appserver
    portforward: true

  PMA:
    type: phpmyadmin
    portforward: true

  appserver:
    run:
      - 'composer install'
      - 'php artisan migrate:fresh --seed'
      - 'php artisan passport:install'

proxy:
  appserver:
    - mijn-doedejaarsma.lndo.site

  mailhog:
    - hog-mijn-doedejaarsma.lndo.site
    - mailhog-mijn-doedejaarsma.lndo.site

  PMA:
    - pma-mijn-doedejaarsma.lndo.site

tooling:
  yarn:
    cmd: cd /app/ && yarn
    command: cd /app/ && yarn
    service: node
